name: Axel J. Solano
markdown: kramdown

introduction: "Hi, my name is Axel. Welcome!"

description: "This site was created to show my resume, projects, skills and is still work in progress."

description2: "Also, If you'd like to contact me, just click on the icons below."

description3: "Hi there! I'm a Data Science Master's graduate from Tufts, passionate about AI's theoretical and practical aspects. My expertise spans statistical learning, NLP, imaging, genetics, and medicine."

description4: "Since April 2023, I've worked at Levin Lab under Dr. Hananel Hazan, focusing on spiking neural networks for BindsNET, and large language models (LLMs)."

description5: "I primarily work with React, React Native, JavaScript, and TypeScript for the front end, and use Next.js, Symfony, PostgreSQL, MySQL, and MongoDB on the back end, deploying mainly on AWS and Vercel."

description6: "My goal is to seamlessly integrate my software development skills with AI to address real-world problems, making a meaningful difference through technology."

description7: "If you're passionate about philosophy, neuroscience, and computer science, and enjoy exploring topics like free will, consciousness, agency, intelligence, cognition, active inference, or the free energy principle, connect with me on LinkedIn."

description8: ""

url: "https://axeljeremy7.github.io"
# url: "http://127.0.0.1:4000"

resume_url: ""

app_urls:
  MyCoolApp:
    url: "https://alyonka.xyz"
    label: "Alyonka App"
    description: "Conversational research agent, AI assistant, and chatbot and mobile app"
  AnotherApp:
    url: "https://dermadora.vercel.app"
    label: "DermaDora App"
    description: "Skincare voice agent"

experience:
  Stealth:
    title: "Founder"
    date: "September 2024 - May 2025" 
    list:
      - Building agents
  Machine Learning Researcher:
    title: "Machine Learning Researcher on Levin Lab"
    date: "April 2023 - June 2025" 
    list:
      - Contributed to the BindsNET project, a Python package for simulating spiking neural networks (SNNs) on CPUs/GPUs using PyTorch, by focusing on the integration of surrogate learning methods to advance biologically inspired machine learning algorithms.
      - Lead exploratory analysis using PEFT, QLoRa, LoRA, fine-tuning, vector databases with in-context-learning on biology and genetics research papers using open-source Large Language Models (LLMs) such as LLaMA, Vicuna, Falcon series to uncover their capabilities.
  Full-Stack Engineer 1:
    title: "Full-Stack & React Native Engineer corePHP"
    date: "September 2019 - June 2022" 
    list:
      - Orchestrated the development of the dspworkplace.com mobile application, enabling real-time chat and push notifications using React Native, Twilio, and Plivo SDKs, and successfully scaled to support an active user base of 1,000-5,000 on iOS and Android platforms.
      - Spearheaded the collective development and launch of the dspworkplace.com web app, focusing on the integration of scheduling events, mobile workflow design, and chatbot functionality to facilitate efficient user interactions.
      - Delivered expert full-stack development and RESTful API consultancy such as fraudsniffr.com, addressing intricate technical challenges and propelling project objectives for diverse clients, with a toolkit comprising Symfony, PHP, HTML, JavaScript, CSS, jQuery, React, .NET, and MySQL/MongoDB, along with AWS for enhanced cloud storage and database optimization.
  # Teaching Assistant/Grader for R Programming for Data Science:
  #   title: "Teaching Assistant/Grader for R Programming for Data Science"
  #   date: "Jan 2018 & 2019 - April 2018 & 2019" 
  #   list:
  #     - Assisted professor in the development of evaluations and multiple learning methods.
  #     - Communicated effectively to students to accelerate their learning process.
  # Teaching Assistant/Grader for Storage, Retrieval & Processing Big Data:
  #   title: "Teaching Assistant/Grader for Storage, Retrieval & Processing Big Data"
  #   date: "September - December 2018" 
  #   list:
  #     - Assisted professor in Hadoop and hardware and software storage. 
  # Teaching Assistant/Grader for Big Data, Cloud & loT:
  #   title: "Teaching Assistant/Grader for Big Data, Cloud & loT"
  #   date: "June - August 2018" 
  #   list:
  #     - Graded and provided feedback for assignments for Google Cloud Services and AWS.
  # Teaching Assistant/Grader for Database Management Systems:
  #   title: "Teaching Assistant/Grader for Database Management Systems"
  #   date: "June - August 2018" 
  #   list:
  #     - Graded and provided feedback for assignments for MySQL databases.
  # Intramural Official:
  #   title: "Intramural Official"
  #   date: "October 2017 - April 2019" 
  #   list:
  #     - Referee for soccer and volleyball.
  #     - Teamwork and coordination with my partner referee to maintain sportsmanship.
  #     - Communicated effectively with players about sport rules and policies.


skills:
  React:
    skill: "React"
    img: ""
  React Native:
    skill: "React Native"
    img: ""  
  Symfony:
    skill: "Next.js"
    img: ""
  Python:
    skill: "Python"
    img: ""
  JS:
    skill: "TypeScript"
    img: ""
  Node.js:
    skill: "Node.js"
    img: ""
  Express:
    skill: "Symfony"
    img: ""
  REST:
    skill: "REST"
    img: ""  
  DeepLearning:
    skill: "Deep Learning"
    img: ""  
  FastAPI:
    skill: "FastAPI"
    img: ""  
  PHP:
    skill: "PHP"
    img: ""
  Keras:
    skill: "Keras"
    img: "" 
  AWS:
    skill: "AWS"
    img: ""
  GCP:
    skill: "GCP"
    img: ""        
  TensorFlow:
    skill: "TensorFlow"
    img: "" 
  PyTorch:
    skill: "PyTorch"
    img: "" 
  LLM:
    skill: "LLM"
    img: "" 
  HuggingFace:
    skill: "HuggingFace"
    img: ""  
  ML:
    skill: "ML"
    img: ""
  Agentic:
    skill: "Agentic SDK"
    img: ""
  C/C++:
    skill: "C/C++"
    img: ""  
    
    

repo_urls:
  React App - Music App:
    url: "https://music-app-1-dba6f.firebaseapp.com"
    label: "React App - Music App"
    icon: ""
  mypage:
    url: "https://github.com/axeljeremy7/axeljeremy7.github.io"
    label: "My GitHub Page"
    icon: ""
  botgroupme:
    url: "https://github.com/axeljeremy7/bot"
    label: "A Groupme Bot"
    icon: ""
  hn:
    url: "https://github.com/axeljeremy7/HackerNews"
    label: "Hacker News on Android"
    icon: ""
  huffman:
    url: "https://github.com/axeljeremy7/HuffmanCode"
    label: "Huffman Code"
    icon: ""
  kruskal:
    url: "https://github.com/axeljeremy7/Kruskal-Algorithm"
    label: "Kruskal Algorithm"
    icon: ""
  knack:
    url: "https://github.com/axeljeremy7/Knapsack-Algorithm"
    label: "Knapsack Algorithm"
    icon: ""
  ml3:
    url: "https://github.com/axeljeremy7/Tree-models"
    label: "Tree model on R"
    icon: ""
  mater1:
    url: "https://axeljeremy7.github.io/materialize1/"
    label: "Materialize Westworld"
    icon: ""
  groupCal:
    url: "https://github.com/axeljeremy7/GroupCalendar"
    label: "Group Calendar website"
    icon: ""
  PUBG:
    url: "https://github.com/axeljeremy7/PUBG"
    label: "PUBG Kaggle - Tree Models and Deep Learning"
    icon: ""
  For SalesPage - Data Matching Problem:
    url: "https://github.com/OryGregS/SeniorProject"
    label: "Fuzzy Record Linkage - Data Matching Problem"
    icon: ""


contact_urls:
  twitter:
    url: "https://x.com/axel_kldiv"
    label: "X/Twitter"
    class: "fa-brands fa-x-twitter"
#   Medium:
#     url: ""
#     label: "Medium"  
#     class: "fa fa-medium"
  linkedin:
    url: "https://www.linkedin.com/in/axel-solano/"
    label: "LinkedIn"
    icon: "/assets/img/white-linkedin-64.png"
    class: "fa-brands fa-linkedin-in"
  github:
    url: "https://github.com/axeljeremy7"
    label: "GitHub"
    icon: "/assets/img/github-64.png"
    class: "fa-brands fa-github"
  substack:
    url: "https://axelkldiv.substack.com/"
    label: "substack"
    class: "fa-brands fa-x-twitter" 
#   email:
#     url: ""
#     label: "Email"
#     value: ""
#     icon: "/assets/img/mail-64.png"
#     class: "fa fa-envelope"

menu:
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "https://axeljeremy7.github.io"
  - title: "Blog"
    url: "/blog"
